### ISSUE TITLE
Nondeterministic extraction of javascript links

### ISSUE THREAD

**Issue by woconnor** [markusmobius/go-domdistiller#2]
Links with a `javascript:` target are nondeterministically extracted. The result varies from execution to execution; these links are randomly included or discarded.

For example, the following snippet 
```
    <ul>
      <li><a href="javascript:void(0);" id="foo">Foo</a></li>
      <li><a href="javascript:void(0);" id="bar">Bar</a></li>
      <li><a href="javascript:void(0);" id="baz">Baz</a></li>
    </ul>
```
Is randomly turned into something like `<ul><li></li><li></li><li>Baz</li></ul>` or `<ul><li>Foo</li><li>Bar</li><li></li></ul>` depending on the execution. See attached file for a complete example.

Ideally the extraction result should be the same every time.

[jslinks.txt](https://github.com/markusmobius/go-domdistiller/files/7034545/jslinks.txt)

**Comment by RadhiFadlillah** [comment]
This should be fixed by [`f1de5e6`][0] and [`9549d74`][1].

[0]: https://github.com/markusmobius/go-domdistiller/commit/f1de5e68990de375e7a0dc6459326da9bba168c1
[1]: https://github.com/markusmobius/go-domdistiller/commit/9549d7422623eb11fdef3d0c5ac15b533515ec50
